config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :home
  resources :contacts

  root 'home#index'

  get 'technologies/:name' => 'home#techs', as: :technologies
  get 'services' => 'home#services'

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :phone, :name, :email, :message, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :contact_us_initiate

  def contact_us_initiate
    @contact = Contact.new
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @c = Contact.new(contact_params)
    p @c.valid?
    if @c.save
      # ...
    else
      flash.now[:error] = "Could not save Contact"
      p @c.errors.messages
   end

    #render :json => @c.name
  end

  private
  # Using a private method to encapsulate the permissible parameters is just a good pattern
  # since you'll be able to reuse the same permit list between create and update. Also, you
  # can specialize this method with per-user checking of permissible attributes.
  def contact_params
    params.require(:contact).permit(:email, :phone, :name, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def techs
    techarr = ['php', 'dotnet', 'testing', 'mobileapp']
    @techname = params[:name]
    unless techarr.include?(@techname)
      redirect to root_path
    end
  end

  def services

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.js.erb
<%content=""%>
<% @c.errors.messages.each do |key,val|%>
<%content += "<li>#{val}</li>"%>

<% end %>
console.log(<%=content%>)
$('.error-list ul').html(<%=content%>)

app/views/home/_dotnet.html.erb
<h2 class="section-heading">Microsoft .NET</h2>

<!--<div class="alert alert-info" role="alert">Website hosting</div>-->
<ol class="lead">
  <li>ASP.NET Development
    <ul>
      <li>Dialectic developers expertise in ASP.NET 4.0 and above versions for designing ASP.NET web
        applications.</li>
    </ul>
  </li>

  <li>Windows Desktop Development
    <ul>
      <li>Dialectic development team develops Windows GUI applications (Windows Forms) and Windows Console applications.</li>
    </ul>
  </li>
  <li>Misceleneous .NET Services
    <ul>

      <li>.NET data management solution with analysis (Microsoft SQLServer, MySQL, ADO.NET, LINQ, Entity Framework)</li>
      <li>Windows Communication Foundation (WCF)</li>
      <li>ASP.NET Web Services development, Migration of ASP.NET Web Services to WCF</li>
      <li>Windows Runtime Components development</li>
      <li>.NET Application Maintenance and Support</li>
    </ul>

  </li>
</ol>

app/views/home/_mobileapp.html.erb
<h2 class="section-heading">iOS/Android</h2>

<p class="lead"><strong>iOS Application Development</strong></p>
<p class="lead">Our Services:</p>
<ul class="lead">
<li>Custom application developement</li>
  <li>Mobile web developement</li>
  <li>Widget Developement</li>
  <li>Software QA and testing</li>
  <li>Software support and maintenance</li>
  <li>Web application Developement</li>
</ul>
<p class="lead">Technologies:</p>
<p class="lead">Dialectic's team of iOS developers have good knowledge and experience in iOS application development using iphone/ipad/ipod and iphone supported technologies.</p>


<p class="lead"><strong>Android Application Development</strong></p>
<p class="lead">Our Services:</p>
<ul class="lead">
  <li>Widget Development</li>
  <li>Application Development</li>
  <li>API Customisation</li>
  <li>Support & Maintenance</li>
  <li>QA/Testing</li>
  <li>Porting/Migration to different Android platforms</li>
  <li>Android development on 2.x (Phone)/ 3.x (Tablet)/ 4.x (Phone and Tablet)</li>
</ul>
<p class="lead">Technologies:</p>
<p class="lead">Our Android experts make use of the comprehensive set of development tools offered by the Android SDK to create applications which add value to our customers.
  Utilities such as Android SDK's APIs, handset emulator, sample code and debugging tools are extensively used by them to create risk-free and highly valued Android applications.
</p>

app/views/home/_php.html.erb
<h2 class="section-heading">PHP</h2>

<!--<div class="alert alert-info" role="alert">Website hosting</div>-->
<p class="lead">We provide expert offshore PHP development services from India, gaining its expertise from years of experience in PHP web development and PHP application development.</p>

<ul class="lead">
  <li>Web Application Development</li>
  <li>Programming and Scripting</li>
  <li>Product Development</li>
  <li>Porting and Migration</li>
  <li>Content Management Systems</li>
</ul>

app/views/home/_testing.html.erb
<h2 class="section-heading">Testing</h2>

<!--<div class="alert alert-info" role="alert">Website hosting</div>-->
<p class="lead">We expertise in Quality Assurance testing services. Right from test strategy to test plans to generating test cases to testing, we provide high quality testing services and make sure  the application is robust.
  We summarize our testing cycle with a detailed Test Sumary Report.</p>


<ul class="lead testing-list">

  <li><%= image_tag 'testing-web.png' %></li>
  <li><%= image_tag 'testing-mob.png' %></li>
  <li><%= image_tag 'testing-desktop.png' %></li>
  <li><%= image_tag 'testing-auto.png' %></li>
</ul>

app/views/home/index.html.erb
<!-- Header -->
<div class="intro-header">

  <div class="container">

    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message">

        </div>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>
<!-- /.intro-header -->

<!-- Page Content -->

<div class="content-section-a">

  <div class="container">

    <div class="row">
      <div class="col-lg-7 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">Who We Are</h2>

        <!--<div class="alert alert-info" role="alert">Website hosting</div>-->
        <p class="lead">Dialectic Technologies is a non-traditional software company with a focus on customer centric business. We believe that with mutual co-operation and partnership no stone can remain unturned. We foster a collaborative environment with our clients and help them achieve their business milestones.
          We are eager to try new things. We love what we do and love sharing our knowledge capital with like minded thinkers, doers and innovators. Our deliberate push for certainty is a must lookout for our clients and assurance is a fact we are built upon.</p>
      </div>
      <div class="col-lg-5 col-sm-6">
        <%= image_tag 'dialectic-d.png', :class => 'img-responsive what-we-do-img' %>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>
<!-- /.content-section-a -->

<div class="content-section-a">

  <div class="container">

    <div class="row">
      <div class="col-lg-12 col-sm-12">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">What We Do</h2>

        <!--<p class="lead">Web apps that run on Android and iOS.</p>-->

        <div class="services-list">

          <%= link_to (image_tag 'webapp.png', :class => 'img-responsive'), '#' %>
          <%= link_to (image_tag 'mobileapp.png', :class => 'img-responsive'), '#' %>
          <%= link_to (image_tag 'maintenance.png', :class => 'img-responsive'), '#' %>
          <%= link_to (image_tag 'qa.png', :class => 'img-responsive'), '#' %>

        </div>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>
<!-- /.content-section-b -->

app/views/home/services.html.erb
<!-- Page Content -->

<div class="content-section-a">

  <div class="container">

    <div class="row">
      <div class="col-lg-7 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">Web Application Development</h2>
        <p class="lead">
          Dialectic Technologies, being one of the leading web application development companies, allows you to have a beautiful web presence through website with our great web development solutions, exactly according to requirements. Our team of professionals has expertise in developing any type of website usign any platform by properly understanding your needs and by going with your thoughts. We focus to deliver high quality website development service throughout the process and bring into some basic features of a successful website.
        </p>
      </div>
      <div class="col-lg-5 col-sm-6">
        <%= image_tag 'webapp.png', :class => 'img-responsive ' %>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>

<div class="content-section-a">

  <div class="container">

    <div class="row">
      <div class="col-lg-7 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">Mobile Application Development</h2>

        <!--<div class="alert alert-info" role="alert">Website hosting</div>-->
        <p class="lead">
        We design low signature, high performance applications that suit the wireless platforms. The service we provide are:
          <ul class="lead">
            <li>Custom application development</li>
            <li>  Handset compatibility and porting</li>
            <li>Quality Assurance and testing</li>
            <li>Security and privacy</li>
            <li> Games development</li>
          </ul>
        </p>
      </div>
      <div class="col-lg-5 col-sm-6">
        <%= image_tag 'mobileapp.png', :class => 'img-responsive ' %>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>

<div class="content-section-a">

  <div class="container">

    <div class="row">
      <div class="col-lg-7 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">Maintenance</h2>

        <!--<div class="alert alert-info" role="alert">Website hosting</div>-->
        <p class="lead">
          Dialectic Technologies provides focused expertise in support and maintenance of software.
          Various facets of software maintenance we undertake include:
            <ul class="lead">
              <li>Code maintenance</li>
              <li>Bug fixing</li>
              <li>Version, patch and release management</li>
              <li>Software upgrade</li>
              <li>Code optimization</li>
            </ul>
        </p>
      </div>
      <div class="col-lg-5 col-sm-6">
        <%= image_tag 'maintenance.png', :class => 'img-responsive ' %>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>

<div class="content-section-a">

  <div class="container">

    <div class="row">
      <div class="col-lg-7 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">QA/Testing</h2>

        <!--<div class="alert alert-info" role="alert">Website hosting</div>-->
        <p class="lead">
          Dialectic Technologies Testing Practice has a unique combination of skilled software engineering & testing teams with proven expertise in testing tools and methodologies for a wide range of solutions.This includes new application/ product testing, support and integration.
          The team has experience and focus on testing, both as part of the development team and as an external authority. Expertise covers test-plan development, test-case development, regression testing, bug maintenance, debug management and certification. Automated test scripts are developed where appropriate.
        </p>
      </div>
      <div class="col-lg-5 col-sm-6">
        <%= image_tag 'qa.png', :class => 'img-responsive ' %>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>

<!-- /.content-section-a -->

app/views/home/techs.html.erb
<!-- Page Content -->

<div class="content-section-a tech-content">

  <div class="container">

    <div class="row">
      <div class="col-lg-7 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>

        <%= render "#{@techname}" %>

      </div>
      <div class="col-lg-5  col-sm-6">
        <%= image_tag "ico-tech-#{@techname}.png", :class => 'img-responsive tech-img' %>
      </div>
    </div>

  </div>
  <!-- /.container -->

</div>
<!-- /.content-section-a -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dialectic Technologies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('dialectic-small.png'), root_path, :class => "navbar-brand" %>

    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#">About</a>
        </li>
        <li>
          <%= link_to 'Services', services_path %>
        </li>
        <li class="dropdown">
          <a aria-expanded="false" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#">Technologies <span class="caret"></span></a>
          <ul role="menu" class="dropdown-menu">
            <li><%= link_to "PHP", technologies_url(name: 'php') %> </li>
            <li><%= link_to ".NET", technologies_url(name: 'dotnet') %></li>
            <li><%= link_to "Testing", technologies_url(name: 'testing') %></li>
            <li><%= link_to "iOS/Android", technologies_url(name: 'mobileapp') %></li>
          </ul>
        </li>
        <li>
          <a href="javascript:void(0)" data-toggle="modal" data-target="#contactModal">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>
<%= yield %>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-inline">
          <li>
            <a href="#home">Home</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="#about">About</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="#services">Services</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="#">Technologies</a>
          </li>
          <li class="footer-menu-divider">&sdot;</li>
          <li>
            <a href="#contact">Contact</a>
          </li>
        </ul>
        <p class="copyright text-muted small">Copyright &copy; Dialectic Technologies 2015. All Rights Reserved</p>
      </div>
    </div>
  </div>
</footer>

<%= render 'layouts/shared/modals' %>
</body>
</html>

app/views/layouts/shared/_modals.html.erb
<!--contact us modal-->
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Contact Us</h4>
      </div>
      <%= form_for @contact, url: contacts_path, html: {class: "form-horizontal"}, :remote => true do |f| %>
      <div class="modal-body">

        <div class="error-list"><ul></ul></div>

          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
              <%= f.text_field :name, :class => 'form-control', :placeholder => 'Name' %>
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <%= f.email_field :email, :class => 'form-control', :placeholder => 'Email' %>
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Phone</label>
            <div class="col-sm-10">
              <%= f.text_field :phone, :class => 'form-control', :placeholder => 'Phone' %>
            </div>
          </div>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Message</label>
            <div class="col-sm-10">
              <%= f.text_area :message, :class => 'form-control', :placeholder => 'Enter Message' %>
            </div>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Send Message', :class => 'btn btn-primary' %>
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->